# Generated by Django 4.0.5 on 2022-08-14 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidneyStoneDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignal_image', models.ImageField(upload_to='kidney_stones/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='kidney_stones/')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_stone_detected', models.BooleanField(default=False)),
                ('number_of_stones', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_kidney_stones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
